
--INSERTING USER
INSERT INTO "user"
(id, username, email, password, first_name, last_name)
VALUES(1, 'admin', 'admin1@gmail.com', 'sha256$oBgJRJIajQTsgjRV$eeb764ccce2678b3788987258307f1f552b8e4b19c6c75003302bfe3f8a43c1f', 'Admin', 'User');

--INSERT CATEGORIES
INSERT INTO category (id, name) VALUES(1, 'Breakfast');
INSERT INTO category (id, name) VALUES(2, 'Lunch');
INSERT INTO category (id, name) VALUES(3, 'Dinner');

--INSERT DIFFICULTIES
INSERT INTO difficulty (id, difficulty) VALUES(1, 'Beginner');
INSERT INTO difficulty (id, difficulty) VALUES(2, 'Intermediate');
INSERT INTO difficulty (id, difficulty) VALUES(3, 'Advanced');

INSERT INTO recipe (user_id, name, instructions, hours_to_make, minutes_to_make, calories, description, image, ingredients, category_id, difficulty_id)
VALUES 
(1,"Spaghetti Carbonara","Step 1: Cook spaghetti in a large pot of salted boiling water until al dente.¦Step 2: In a bowl, whisk together eggs, grated Pecorino Romano cheese, and black pepper.¦Step 3: In a skillet, cook diced pancetta until crispy.¦Step 4: Add cooked spaghetti to the skillet with pancetta and toss to combine.¦Step 5: Remove from heat and quickly stir in the egg and cheese mixture.¦Step 6: Serve immediately, garnished with more cheese and black pepper.",0,20,450,"A classic Italian pasta dish made with eggs, Pecorino Romano cheese, pancetta, and black pepper.","../static/Images/spaghetti-carbonara.jpeg","8 oz spaghetti¦3 large eggs¦1 cup grated Pecorino Romano cheese¦4 oz diced pancetta¦Salt and black pepper to taste",3,1),
(1,"Buffalo Chicken Mac and Cheese","Step 1: Preheat your oven to 375Â°F (190Â°C).¦Step 2: Cook the macaroni in a large pot of salted boiling water until al dente. Drain and set aside.¦Step 3: In a skillet, cook boneless, skinless chicken breasts until fully cooked. Shred the chicken into small pieces and set aside.¦Step 4: In a separate saucepan, melt butter over medium heat. Stir in all-purpose flour and cook for a few minutes until it forms a roux.¦Step 5: Gradually whisk in milk and bring to a simmer. Let it cook until the sauce thickens.¦Step 6: Add shredded cheddar cheese and cream cheese to the sauce, stirring until it's smooth and creamy.¦Step 7: Mix in hot sauce (adjust to taste), diced celery, and cooked chicken pieces.¦Step 8: Combine the cooked macaroni with the cheese sauce mixture.¦Step 9: Transfer the mixture to a baking dish and bake in the preheated oven for 25-30 minutes or until bubbly and golden brown.¦Step 10: Serve hot and garnish with chopped green onions.",0,45,600,"Buffalo Chicken Mac and Cheese is a delightful fusion of spicy buffalo chicken, creamy mac and cheese, and a hint of celery for a classic buffalo wing flavor.","../static/Images/buffalo-chicken-mac-cheese.jpeg","8 oz macaroni¦2 boneless, skinless chicken breasts¦1/4 cup butter¦1/4 cup all-purpose flour¦2 cups milk¦2 cups shredded cheddar cheese¦4 oz cream cheese¦1/2 cup hot sauce¦1/2 cup diced celery¦Salt and black pepper to taste¦Chopped green onions for garnish",3,2),
(1,"Chicken Salad","Step 1: Cook and shred chicken breast.¦Step 2: Mix shredded chicken with mayonnaise, diced celery, and grapes.¦Step 3: Season with salt and pepper to taste.¦Step 4: Serve chilled.",0,15,300,"A simple and delicious chicken salad with a mix of flavors and textures.","../static/Images/chicken-salad.webp","2 cups cooked chicken breast, shredded¦1/2 cup mayonnaise¦1/2 cup diced celery¦1/2 cup grapes, halved¦Salt and pepper to taste",2,1),
(1,"Spaghetti","Step 1: Cook spaghetti in a large pot of salted boiling water until al dente.¦Step 2: In a skillet, heat olive oil and sautÃ© minced garlic until fragrant.¦Step 3: Add diced tomatoes and tomato sauce to the skillet. Simmer for a few minutes.¦Step 4: Season the sauce with salt, black pepper, and red pepper flakes (adjust to taste).¦Step 5: Toss cooked spaghetti with the sauce and fresh basil leaves.¦Step 6: Serve hot, garnished with grated Parmesan cheese.",0,25,350,"A simple and flavorful spaghetti dish with a homemade tomato sauce and fresh basil.","../static/Images/spaghetti.jpeg","8 oz spaghetti¦2 cloves garlic, minced¦1 cup diced tomatoes¦1 cup tomato sauce¦2 tablespoons olive oil¦Salt, black pepper, and red pepper flakes to taste¦Fresh basil leaves for garnish¦Grated Parmesan cheese for garnish",2,1),
(1,"Empanadas","Step 1: In a large mixing bowl, combine all-purpose flour, salt, and cold butter. Mix until it forms a crumbly texture.¦Step 2: Gradually add cold water and knead the dough until it's smooth.¦Step 3: Roll out the dough and cut it into circles.¦Step 4: In a separate bowl, mix ground beef, diced onions, hard-boiled eggs, olives, and spices.¦Step 5: Place the filling in the center of each dough circle and fold it in half, sealing the edges.¦Step 6: Brush the empanadas with beaten egg and bake in a preheated oven until golden brown.¦Step 7: Serve hot and enjoy!",0,50,250,"Empanadas are a delightful Latin American snack with a flavorful beef filling and a flaky pastry crust.","../static/Images/empanadas.webp","2 cups all-purpose flour¦1/2 teaspoon salt¦1 cup cold butter, cubed¦1/2 cup cold water¦1/2 lb ground beef¦1/2 cup diced onions¦2 hard-boiled eggs, chopped¦1/4 cup green olives, sliced¦1/2 teaspoon cumin¦Salt and pepper to taste¦1 egg, beaten (for brushing)",3,2),
(1,"Chicken and Waffles","Step 1: Preheat your waffle iron according to the manufacturer's instructions.¦Step 2: In a mixing bowl, combine all-purpose flour, sugar, baking powder, and salt.¦Step 3: In a separate bowl, whisk together eggs, buttermilk, and melted butter.¦Step 4: Pour the wet ingredients into the dry ingredients and stir until just combined.¦Step 5: Pour the waffle batter into the preheated waffle iron and cook until golden and crisp.¦Step 6: While the waffles are cooking, season chicken pieces with salt, black pepper, and paprika.¦Step 7: Heat oil in a skillet and fry the chicken until it's crispy and cooked through.¦Step 8: Serve the fried chicken on top of the freshly cooked waffles.¦Step 9: Drizzle with maple syrup and garnish with chopped parsley.",0,30,600,"Chicken and Waffles is a classic Southern dish that combines crispy fried chicken with fluffy waffles, topped with sweet maple syrup.","../static/Images/chicken-and-waffle.webp","1 cup all-purpose flour¦2 tablespoons sugar¦1 teaspoon baking powder¦1/2 teaspoon salt¦2 large eggs¦1 cup buttermilk¦2 tablespoons melted butter¦4 boneless, skinless chicken thighs¦Salt, black pepper, and paprika to taste¦Vegetable oil for frying¦Maple syrup for drizzling¦Chopped parsley for garnish",1,3),
(1,"Eggs Benedict","Step 1: Fill a saucepan with a few inches of water and bring it to a simmer.¦Step 2: In a heatproof bowl, whisk together egg yolks, lemon juice, and a pinch of cayenne pepper.¦Step 3: Place the bowl over the simmering water (double boiler) and whisk continuously until the mixture thickens to form a hollandaise sauce. Remove from heat and keep warm.¦Step 4: In a separate saucepan, melt butter over low heat. Skim off and discard the white milk solids from the surface, leaving clarified butter. Keep it warm.¦Step 5: In a skillet, bring water to a gentle simmer and add white vinegar. Create a whirlpool in the water using a spoon and gently slide in an egg. Poach the egg for about 3-4 minutes until the white is set and the yolk is still runny. Repeat for each egg.¦Step 6: Toast English muffin halves until lightly browned.¦Step 7: Place a slice of Canadian bacon on each muffin half, followed by a poached egg.¦Step 8: Spoon hollandaise sauce generously over each egg.¦Step 9: Garnish with chopped chives or parsley.¦Step 10: Serve immediately and enjoy!",0,20,400,"Eggs Benedict is a classic brunch dish featuring poached eggs, Canadian bacon, and hollandaise sauce served on toasted English muffins.","../static/Images/Egg-Benedict.jpeg","4 large egg yolks¦1 tablespoon lemon juice¦A pinch of cayenne pepper¦1/2 cup (1 stick) unsalted butter¦2 teaspoons white vinegar¦4 large eggs¦2 English muffins, split and toasted¦4 slices Canadian bacon¦Chopped chives or parsley for garnish",1,3),
(1,"Breakfast Burritos","Step 1: In a skillet, cook ground breakfast sausage over medium heat until browned and crumbled. Drain excess fat.¦Step 2: Add diced onions, bell peppers, and minced garlic to the skillet. Cook until the vegetables are tender.¦Step 3: In a bowl, whisk together eggs, salt, and black pepper. Pour the egg mixture into the skillet with the sausage and vegetables.¦Step 4: Cook, stirring occasionally, until the eggs are scrambled and fully cooked.¦Step 5: Warm the flour tortillas in a dry skillet or microwave until pliable.¦Step 6: Place a portion of the egg and sausage mixture in the center of each tortilla.¦Step 7: Sprinkle shredded cheese over the egg mixture and drizzle with hot sauce (if desired).¦Step 8: Fold in the sides of the tortilla and then roll it up tightly to form a burrito.¦Step 9: Serve the breakfast burritos with salsa and sour cream on the side.¦Step 10: Enjoy your delicious breakfast burritos!",0,20,350,"Breakfast Burritos are a satisfying morning meal featuring savory sausage, scrambled eggs, and melted cheese wrapped in a warm tortilla.","../static/Images/break-burrito.jpeg","1/2 lb ground breakfast sausage¦1/4 cup diced onions¦1/4 cup diced bell peppers¦2 cloves garlic, minced¦6 large eggs¦Salt and black pepper to taste¦4 large flour tortillas¦1 cup shredded cheddar cheese¦Hot sauce (optional)¦Salsa and sour cream for serving",1,2),
(1,"Chicken Alfredo","Step 1: Cook fettuccine in boiling salted water until al dente.¦Step 2: In a skillet, sautÃ© diced chicken breasts until cooked through.¦Step 3: In a separate pan, melt butter and add minced garlic, heavy cream, and Parmesan cheese.¦Step 4: Combine cooked fettuccine and chicken with the Alfredo sauce.¦Step 5: Season with salt and pepper to taste.¦Step 6: Garnish with chopped parsley and serve hot.",0,30,600,"A creamy pasta dish with tender chicken, fettuccine, and a rich Alfredo sauce.","../static/Images/Chicken-Alfredo.jpeg","12 oz fettuccine¦1.5 lbs chicken breasts, diced¦1 cup heavy cream¦1 cup grated Parmesan cheese¦2 cloves garlic, minced¦Salt and black pepper to taste¦Chopped parsley for garnish",3,2),
(1,"Margherita Pizza","Step 1: Preheat the oven to 475Â°F (245Â°C).¦Step 2: Roll out pizza dough on a floured surface and transfer to a pizza stone or baking sheet.¦Step 3: Spread tomato sauce over the dough, leaving a border for the crust.¦Step 4: Arrange sliced fresh mozzarella and cherry tomatoes on top.¦Step 5: Drizzle with olive oil and sprinkle with fresh basil leaves.¦Step 6: Bake in the preheated oven for 12-15 minutes or until the crust is golden and the cheese is melted.¦Step 7: Remove from the oven, let it cool slightly, then slice and serve.",0,25,400,"A classic Margherita pizza with fresh tomatoes, mozzarella, and basil.","../static/Images/marg-pizza.jpeg","1 lb pizza dough¦1/2 cup tomato sauce¦8 oz fresh mozzarella, sliced¦1 cup cherry tomatoes, halved¦2 tbsp olive oil¦Fresh basil leaves for garnish¦Salt and black pepper to taste",2,1),
(1,"Avocado Toast with Poached Egg","Step 1: Toast whole-grain bread slices to your liking.¦Step 2: Mash ripe avocados and spread over the toasted bread.¦Step 3: Poach eggs in simmering water until whites are set but yolks are still runny.¦Step 4: Carefully place a poached egg on each avocado toast.¦Step 5: Season with salt, black pepper, and optional toppings like red pepper flakes or fresh herbs.¦Step 6: Serve immediately for a delicious and nutritious breakfast!",0,15,350,"A simple and healthy breakfast featuring creamy avocado and a perfectly poached egg on whole-grain toast.","../static/Images/avocado-toast.jpeg","4 slices whole-grain bread¦2 ripe avocados¦4 large eggs¦Salt and black pepper to taste¦Optional: red pepper flakes, fresh herbs for garnish",1,1),
(1,"Blueberry Pancakes","Step 1: In a bowl, whisk together flour, baking powder, sugar, and a pinch of salt.¦Step 2: In a separate bowl, whisk together milk, eggs, and melted butter.¦Step 3: Combine wet and dry ingredients until just mixed; fold in fresh blueberries.¦Step 4: Heat a griddle or skillet and pour 1/4 cup batter for each pancake.¦Step 5: Cook until bubbles form on the surface, then flip and cook until golden brown.¦Step 6: Serve the pancakes with maple syrup and additional blueberries.",0,30,450,"Fluffy pancakes bursting with juicy blueberries, perfect for a delightful breakfast.","../static/Images/blueberry-panckaes.jpeg","2 cups all-purpose flour¦2 tbsp sugar¦2 tsp baking powder¦1/2 tsp salt¦2 cups milk¦2 large eggs¦1/4 cup melted butter¦1 cup fresh blueberries¦Maple syrup for serving",1,2),
(1,"Smoked Salmon Eggs Benedict","Step 1: Prepare hollandaise sauce by whisking egg yolks, lemon juice, and a pinch of cayenne over a double boiler; slowly drizzle in melted butter until thickened.¦Step 2: Toast English muffins and top with smoked salmon slices.¦Step 3: Poach eggs to medium doneness and place one on each muffin half.¦Step 4: Spoon hollandaise sauce over poached eggs and garnish with fresh dill.¦Step 5: Serve immediately, and enjoy this elevated version of Eggs Benedict!",0,45,550,"A luxurious and flavorful breakfast dish featuring smoked salmon, perfectly poached eggs, and a rich hollandaise sauce.","../static/Images/smoked-salmon.jpeg","4 English muffins, split and toasted¦8 oz smoked salmon¦4 large eggs¦Fresh dill for garnish¦Salt and black pepper to taste¦Hollandaise sauce ingredients: 3 large egg yolks, 1 tbsp lemon juice, 1/2 cup unsalted butter, cayenne pepper to taste",1,3),
(1,"Quinoa and Roasted Vegetable Salad","Step 1: Cook quinoa according to package instructions and let it cool.¦Step 2: Toss mixed vegetables (bell peppers, zucchini, cherry tomatoes) with olive oil, salt, and pepper; roast until tender.¦Step 3: Prepare a lemon-tahini dressing by mixing tahini, lemon juice, garlic, and water.¦Step 4: Combine quinoa, roasted vegetables, and dressing in a large bowl.¦Step 5: Add feta cheese, chopped fresh herbs, and toasted pine nuts; toss gently to combine.¦Step 6: Serve the salad chilled, and enjoy a nutritious and flavorful lunch!",0,50,400,"A hearty and colorful salad featuring quinoa, roasted vegetables, feta cheese, and a zesty lemon-tahini dressing.","../static/Images/roasted-veggie-quinoa.jpeg","1 cup quinoa¦2 cups mixed vegetables (bell peppers, zucchini, cherry tomatoes)¦2 tbsp olive oil¦Salt and black pepper to taste¦1/2 cup crumbled feta cheese¦2 tbsp fresh herbs (parsley, basil), chopped¦2 tbsp pine nuts, toasted¦Dressing ingredients: 1/4 cup tahini, 2 tbsp lemon juice, 1 clove garlic (minced), 2 tbsp water",2,3),
(1,"Beef Wellington","Step 1: Season beef tenderloin with salt and black pepper; sear on all sides in a hot pan with oil.¦Step 2: Brush the beef with Dijon mustard and wrap it in prosciutto slices.¦Step 3: Roll out puff pastry, place the beef in the center, and encase it tightly.¦Step 4: Brush the pastry with egg wash and bake until golden brown and cooked to your liking.¦Step 5: Rest before slicing into portions, and serve this elegant Beef Wellington.",0,2,800,"A classic and impressive dish featuring beef tenderloin, prosciutto, and puff pastry, baked to perfection.","../static/Images/beef-wellington.jpeg","2 lbs beef tenderloin¦Salt and black pepper to taste¦2 tbsp Dijon mustard¦8 slices prosciutto¦1 lb puff pastry, thawed if frozen¦1 egg (beaten, for egg wash)¦2 tbsp olive oil",3,3);
